[tool.poetry]
name = "osa2"
version = "0.1.0"
description = ""
authors = ["jkhaimi <jesse.haimi@icloud.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
toml = "^0.10.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
